spring:
  application:
    name: finsight-ai
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 2000ms

  datasource:
    url: jdbc:postgresql://localhost:5432/finsight_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html


application:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 900000        # 15 minutes in milliseconds
    refresh-expiration: 604800000  # 7 days in milliseconds


logging:
  level:
    org.springframework.security.config.annotation.authentication.configuration: ERROR
    org.springframework.cache: TRACE



