spring:
  application:
    name: finsight-ai
  data:
    redis:
      host:  ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379
      connect-timeout: 2000ms

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/finsight_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html


application:
  jwt:
    secret: ${APPLICATION_JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiration: ${APPLICATION_JWT_EXPIRATION:900000}       # 15 minutes in milliseconds
    refresh-expiration: ${APPLICATION_JWT_REFRESH_EXPIRATION:604800000}  # 7 days in milliseconds
  ai:
  gemini:
    api-key: ${GEMINI_API_KEY:AIzaSyDaxdc_phWtZk3_ciGya5rWqQ3KkqzhSmw}
    model: gemini-1.5-flash
    temperature: 0.7


logging:
  level:
    org.springframework.security.config.annotation.authentication.configuration: ERROR
    org.springframework.cache: TRACE


